package main

import (
	"encoding/json"
	"io"
	"net/http"
	"strings"
)
type AutoGenerated struct {
	Data struct {
		ID                string `json:"id"`
		Rank              string `json:"rank"`
		Symbol            string `json:"symbol"`
		Name              string `json:"name"`
		Supply            string `json:"supply"`
		MaxSupply         string `json:"maxSupply"`
		MarketCapUsd      string `json:"marketCapUsd"`
		VolumeUsd24Hr     string `json:"volumeUsd24Hr"`
		PriceUsd          string `json:"priceUsd"`
		ChangePercent24Hr string `json:"changePercent24Hr"`
		Vwap24Hr          string `json:"vwap24Hr"`
		Explorer          string `json:"explorer"`
	} `json:"data"`
	Timestamp int64 `json:"timestamp"`
}

func get_btc_price() string {
	response, err := http.Get("https://api.coincap.io/v2/assets/bitcoin")
	if err != nil {
		return "0"
	}
	defer response.Body.Close()
	body, err := io.ReadAll(response.Body)
	if err != nil {
		return "0"
	}
	var suren AutoGenerated
	err = json.Unmarshal([]byte(body), &suren)
	if err != nil {
		return "0"
	}
	price := suren.Data.PriceUsd
	price = strings.Split(price, ".")[0] +"."+ strings.Split(price, ".")[1][:2]
	return price
}
